apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: premium-todo
spec:
  parentRefs:
    - name: envoy
  hostnames:
    - www.opsforml.com
    - localhost
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: premium-todo
          port: {{ .Values.service.port }}
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /premium-todo