apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: todo-pg-cluster
spec:
  instances: 3
  bootstrap:
    initdb:
      database: todo
      owner: todouser
      secret:
        name: premium-todo
  storage:
    size: 1Gi
